services:
  seismometer:
    build: .
    container_name: seismometer
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://ryan:Welcome123!@192.168.86.48:27017/seismic?authSource=admin
    restart: unless-stopped
